"""initial schema

Revision ID: 422f7c6e383f
Revises: 
Create Date: 2026-07-17 12:14:49.929860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422f7c6e383f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('trained_on_date', sa.Date(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('active', 'training', 'retired', name='model_version_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version')
    )
    op.create_table('rate_table',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('material_name', sa.String(), nullable=False),
    sa.Column('unit', sa.Enum('sqft', 'kg', 'bag', 'unit', 'tonne', 'cft', name='material_unit'), nullable=False),
    sa.Column('rate_per_unit', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_name', 'unit', 'location', name='uq_rate_material_unit_location')
    )
    op.create_index(op.f('ix_rate_table_material_name'), 'rate_table', ['material_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('otp_code_hash', sa.String(), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'rooms_detected', 'rooms_manual', 'rooms_confirmed', 'constraints_set', 'calculated', 'exported', name='job_status'), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('uploaded_file_path', sa.String(), nullable=True),
    sa.Column('budget_cap', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('material_overrides', sa.JSON(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('room_name', sa.String(), nullable=False),
    sa.Column('room_name_raw', sa.String(), nullable=False),
    sa.Column('room_type', sa.Enum('bedroom', 'kitchen', 'bathroom', 'living_room', 'utility', 'pooja_room', 'store_room', 'balcony', 'corridor', 'other', name='room_type'), nullable=False),
    sa.Column('area_sqft', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('length_ft', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('width_ft', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('ceiling_height_ft', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('wall_thickness_ft', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('floor_type', sa.String(), nullable=False),
    sa.Column('door_count', sa.Integer(), nullable=False),
    sa.Column('window_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('gemini_vision', 'manual', name='room_source'), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_boq_rows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('dims', sa.JSON(), nullable=False),
    sa.Column('theoretical_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('actual_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('boq_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('material_name', sa.String(), nullable=False),
    sa.Column('theoretical_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('correction_factor', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('correction_confidence', sa.Enum('high', 'low', 'fallback', name='correction_confidence'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('sqft', 'kg', 'bag', 'unit', 'tonne', 'cft', name='material_unit'), nullable=False),
    sa.Column('rate_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materials')
    op.drop_table('historical_boq_rows')
    op.drop_table('rooms')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rate_table_material_name'), table_name='rate_table')
    op.drop_table('rate_table')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
