"""add room exception_applied

Revision ID: 49f7f8e0ee84
Revises: 7464f9d06850
Create Date: 2026-08-02 15:20:03.548934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f7f8e0ee84'
down_revision: Union[str, Sequence[str], None] = '7464f9d06850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('exception_applied', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'exception_applied')
    # ### end Alembic commands ###
