"""add user name and oauth identity

Revision ID: 6220a44d05e9
Revises: 46fb3c13e2dc
Create Date: 2026-07-27 02:48:59.672040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6220a44d05e9'
down_revision: Union[str, Sequence[str], None] = '46fb3c13e2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('oauth_subject', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('uq_users_oauth_identity', 'users', ['oauth_provider', 'oauth_subject'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Note: restoring the NOT NULL on hashed_password will fail if any OAuth-only
    accounts exist, since those have no password by design. Delete or assign
    passwords to those rows before downgrading.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_oauth_identity', 'users', type_='unique')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'oauth_subject')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
