"""add room exception_text

Revision ID: 7464f9d06850
Revises: 6220a44d05e9
Create Date: 2026-08-02 15:17:15.693847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7464f9d06850'
down_revision: Union[str, Sequence[str], None] = '6220a44d05e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('exception_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'exception_text')
    # ### end Alembic commands ###
